[profile.default]
src = "src"                    # Carpeta donde se encuentran los contratos fuente
out = "out"                    # Carpeta donde se generarán los artefactos compilados
libs = ["lib"]                 # Carpeta donde se encuentran las bibliotecas externas
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/", # Remapping para OpenZeppelin
    "@forge-std/=lib/forge-std/"                  # Remapping para forge-std
]

# Opciones de optimización
optimizer = true               # Habilitar optimización
optimizer_runs = 200           # Número de ejecuciones para optimización

# Permisos de acceso a archivos
fs_permissions = [
    { access = "read", path = "./" }              # Permitir solo lectura en el directorio actual
]